### ISSUE TITLE
Does not seem to support leaflet 1.x

### ISSUE THREAD

**Issue by spydmobile** [NBTSolutions/Leaflet.Dialog#11]
Leaflet.Dialog.js:45 Uncaught TypeError: Cannot read property 'fire' of undefined

when trying to create a dialog.

**Comment by wambacher** [comment]
no problems with 1.x - check your code or post it

**Comment by NathanMarq** [comment]
@spydmobile I've updated the demo page to use Leaflet 1.2 and I don't see any issues: http://nbtsolutions.github.io/Leaflet.Dialog/

I'll close this issue now and re-open if you have a more specific issue.
