### ISSUE TITLE
catching dialog:closed

### ISSUE THREAD

**Issue by wambacher** [NBTSolutions/Leaflet.Dialog#12]
hi 
      map.on("dialog:closed", function(e) {
         console.log( "e=", e);
      });

does not work. any hints?

**Comment by NathanMarq** [comment]
@wambacher Hmmm I'm not sure about that one! I've added all event listeners to the main demo page here, and it seems to be working properly: http://nbtsolutions.github.io/Leaflet.Dialog/

(The listeners are all attached to console.log()s, so you'll need to open the dev tools)

**Comment by NathanMarq** [comment]
Here is the exact line on the demo:

`map.on('dialog:closed', function(e){ console.log("dialog closed event fired."); });`

That line works - so I'm going to close this issue for now.
