### ISSUE TITLE
Multiple Dialogs Share Single Options Object

### ISSUE THREAD

**Issue by alexlukas** [NBTSolutions/Leaflet.Dialog#14]
Hi,
I just discovered a small bug. When creating multiple dialogs with default options, they all share one options object. This can simply be reproduced by visiting [the demo page](http://nbtsolutions.github.io/Leaflet.Dialog/), and then adding another dialog via the developer console using:

`var diag2 = L.control.dialog().setContent("<h1>Second Dialog</h1>").addTo(map);`

When moving the second dialog away from the first one, and then moving the first one it will jump to the position the second one was moved to, because of the shared `options.anchor`.

A simple fix I use is cloning the options object when initializing the dialog:

```
  initialize: function (options){
    this.options = JSON.parse(JSON.stringify(this.options));
    L.setOptions(this, options);

    this._attributions = {};
  },
```

**Comment by NathanMarq** [comment]
@alexlukas Thanks for letting me know about this!
I've updated the initialize function the same way you did - so that should be all set!

You should be able to get the update with v1.0.4.
