### ISSUE TITLE
CSS depends on Bootstrap

### ISSUE THREAD

**Issue by tstumm** [NBTSolutions/Leaflet.Dialog#15]
Using your plugin without Bootstrap CSS messes up the layout, since Bootstrap sets `box-sizing: border-box;` for each element, which is not the default set by the CSS standard.

Adapting `.leaflet-control-dialog .leaflet-control-dialog-inner` and `.leaflet-control-dialog-resizer` to set `box-sizing` accordingly fixes this issue.

**Comment by NathanMarq** [comment]
@tstumm Thanks for alerting me to this! I've updated the CSS to include `box-sizing` for each of the icon containers. You should be able to get this update in v1.0.4.
