### ISSUE TITLE
Snapping

### ISSUE THREAD

**Issue by pds-amd** [NBTSolutions/Leaflet.Dialog#8]
Good day

I'm fairly new to the world of web development and I absolutely love this Dialog tool!

I was wondering if it would be at all possible to extend this slightly to allow dialogs to snap to a grid or one another?

**Comment by NathanMarq** [comment]
Hey @paulds8,
Thanks! Glad you like it :)

Snapping multiple dialogs together would certainly be an interesting enhancement, though I'm not sure if it's consistent with the "simplicity" goals of the plugin. It would probably require a lot of extra code and complication for the move and resize functionalities. I think this would be a cool feature, but I'm not sure if the complication would be worth it for such a small use case. Feel free to give it a shot and submit a PR for it if you really feel like you'd like to work on it though!

**Comment by pds-amd** [comment]
Hi @NathanMarq !

Thanks for the quick response. I get 100% what you're saying.

For the project I'm working on I'm going to have to extend these dialogs somewhat so I will submit the changes I've made for review once I figure it out. It's the only way to learn at any rate.

An additional thing I think would be amazing would be to have the bottom left corner act as a 'flipper'. Meaning, when clicked, the dialog flips over and there is additional content on the other side. This is actually a more useful use case in general and something I think would make for very interesting visualizations.

**Comment by NathanMarq** [comment]
@paulds8 

Go ahead and fork this repo and set up whatever you need to on your version! Here's a few resources I've found that you might like for your fork:

**JQuery's Draggable "Snap" implementation:**
https://github.com/jquery/jquery-ui/blob/89af4c292eaa5fc1c83437ca71085264dcbef34a/ui/widgets/draggable.js#L1100
(although I feel like there is probably a much simpler solution)

**Flippable card:**
https://codepen.io/Orangetronic/pen/ycIGu
(can probably be implemented easily with another "handle" icon that adds/removes this class when clicked)
